const api = {
  prodDomain: 'http://127.0.0.1:5050',
  devDomain: 'http://127.0.0.1:5050',
  prodWsDomain: 'ws://127.0.0.1:5050/ws',
  devWsDomain: 'ws://127.0.0.1:5050/ws',
  checkCode: '/account/checkCode',
  login: '/account/login',
  register: '/account/register',
  getSysSetting: '/account/getSysSetting',
  loadMyGroup: '/group/loadMyGroup',
  saveGroup: '/group/saveGroup',
  getGroupInfo: '/group/getGroupInfo',
  getGroupInfo4Chat: '/group/getGroupInfo4Chat',
  dissolutionGroup: '/group/dissolutionGroup',
  leaveGroup: '/group/leaveGroup',
  addOrRemoveGroupUser: '/group/addOrRemoveGroupUser',
  search: '/contact/search',
  applyAdd: 'contact/applyAdd',
  loadApply: '/contact/loadApply',
  deaWithApply: 'contact/deaWithApply',
  loadContact: '/contact/loadContact',
  getContactUserInfo: '/contact/getContactUserInfo',
  addContact2BlackList: '/contact/addContact2BlackList',
  delContact: '/contact/delContact',
  getContactInfo: '/contact/getContactInfo',
  saveUserInfo: '/userInfo/saveUserInfo',
  getUserInfo: '/userInfo/getUserInfo',
  updatePassword: '/userInfo/updatePassword',
  logout: '/userInfo/logout',
  sendMessage: '/chat/sendMessage',
  uploadFile: '/chat/uploadFile',
  loadAdminAccount: '/admin/loadAdminAccount',
  updateUserStatus: '/admin/updateUserStatus',
  forceOffLine: '/admin/forceOffLine',
  loadGroup: '/admin/loadGroup',
  adminDissolutionGroup: '/admin/dissolutionGroup',
  saveSysSetting: '/admin/saveSysSetting',
  loadSysSetting4Admin: '/admin/loadSysSetting4Admin',
  delUpdate: '/admin/delUpdate',
  saveUpdate: '/admin/saveUpdate',
  postUpdate: '/admin/postUpdate',
  loadBeautyAccount: '/admin/loadBeautyAccountList',
  saveBeautyAccount: '/admin/saveBeautyAccount',
  delBeautyAccount: '/admin/delBeautyAccount',
  checkVersion: '/update/checkVersion'
}

export default api
